### ISSUE TITLE
Add more websites to the hackathon section

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [starlightknown/Cyberon#11]
Website I know to find quality hackathons. (May repeat with currently present)
- https://mlh.io/
- https://devpost.com/hackathons
- https://devfolio.co/hackathons/
- https://gitcoin.co/hackathons
- https://angelhack.com/global-hackathon-series-2021/
- https://hackathons.hackclub.com/
- https://www.incubateind.com/
- https://skillenza.com/

If I find more I will add them soon as well

**Comment by starlightknown** [comment]
I have added those new ones, I'll keep it open for more. thank you
