### ISSUE TITLE
Missing feature in Readme

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [starlightknown/Cyberon#33]
**Describe the bug**
Something is missing in the Project Board probably an Image
**To Reproduce**
Readme.md file

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/70568620/118307311-26305680-b508-11eb-9d5d-3bd5fafae9b4.png)

**Comment by eddiejaoude** [comment]
I will work on this 🤓 

<img width="2080" alt="Screenshot 2021-05-14 at 18 30 00" src="https://user-images.githubusercontent.com/624760/118307491-ae9c0080-b4e2-11eb-87a2-b03888933c2f.png">

**Comment by starlightknown** [comment]
@all-contributors please add @eddiejaoude  for design

**Comment by starlightknown** [comment]
@all-contributors please add @Prathamesh-Shanbhag  for bug
