### ISSUE TITLE
Github pages deployment issue

### ISSUE THREAD

**Issue by Vyvy-vi** [starlightknown/Cyberon#34]
**Describe the bug**
The repo has a github-pages environment, however the deployment displays an error, when you try to open it.

**To Reproduce**
Go to https://starlightknown.github.io/Cyberon

**Expected behavior**
Open a github pages site

**Screenshots**
![Screenshot 2021-05-14 at 11 00 46 PM](https://user-images.githubusercontent.com/62864373/118307375-3d6f4400-b508-11eb-9519-37da884b76a4.png)
![Screenshot 2021-05-14 at 11 01 05 PM](https://user-images.githubusercontent.com/62864373/118307413-48c26f80-b508-11eb-8f20-add6385865df.png)

**Comment by starlightknown** [comment]
@all-contributors please add @Vyvy-vi  for bug

**Comment by starlightknown** [comment]
closed via #65
