### ISSUE TITLE
Docs: Improve README

### ISSUE THREAD

**Issue by vinzvinci** [starlightknown/Cyberon#38]
I suggest improve your documentation, ex:

# Cyberon 
A cool discord bot for hackathon discord servers.

![Untitled](https://user-images.githubusercontent.com/73097560/118307578-782fa700-b51d-11eb-8c74-80d470b6db14.png)

Improve the badges and balance the height into one line.

**Comment by starlightknown** [comment]
lol yep, a better description needed

**Comment by starlightknown** [comment]
@all-contributors please add @vinzvinci  for documentation
