### ISSUE TITLE
Pull Request Template

### ISSUE THREAD

**Issue by AllanRegush** [starlightknown/Cyberon#48]
I think there should be a PR request template to help standardise.

**Comment by verma-kunal** [comment]
i'd like to create one here !!

**Comment by starlightknown** [comment]
Sure, go ahead

**Comment by verma-kunal** [comment]
Should i also create the `.md` file for this & add the template there ?

**Comment by starlightknown** [comment]
Yep in .github folder you have to create a pull_request_template.md file

**Comment by verma-kunal** [comment]
yes! created

**Comment by verma-kunal** [comment]
i've taken example from the EddieHub Support Repo (with some changes) if thats okay, otherwise I can change the whole text
