### ISSUE TITLE
make the badges of single type and add some more

### ISSUE THREAD

**Issue by Umesh-01** [starlightknown/Cyberon#94]
## Description
The badges are of different type (see the image). Add some more badges to the top of readme.md file, since the badges will be colorful and more attractive than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

## Describe the solution you'd like

![image](https://user-images.githubusercontent.com/83420185/124015693-92a4dd80-da02-11eb-80f4-c55a368df5c5.png)

I will add some more badges and also will add links related to them so that the README.md file will look more interactive and awesome.

- [ ] I will align them to the center
- [ ] I will add some more badges
- [ ] I will add links to the badges
- [ ] I will make them all of single type

### Work under/as

- [x] LGMSOC
- [ ] Contributor

**Comment by Umesh-01** [comment]
@starlightknown should I make these changes??

**Comment by starlightknown** [comment]
sure go ahead, is this from LGMSOC?
